version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - misspell
    - modernize
    - nolintlint
    - perfsprint
    - revive
    - unconvert
    - usestdlibvars
    - usetesting

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra:
        group-params: true
        clothe-returns: true
        balance-calls: true

issues:
  fix: true
